# Generated by Django 2.2.5 on 2020-01-09 09:04

from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2024)),
                ('size', sizefield.models.FileSizeField(help_text='size of quota in bytes')),
                ('email_address', models.CharField(blank=True, help_text='email address of user for notifications', max_length=2024, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestoreDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountpoint', models.CharField(blank=True, help_text='E.g. /badc/restore_1', max_length=1024, unique=True)),
                ('allocated_bytes', sizefield.models.FileSizeField(default=0, help_text='Maximum size on the disk that can be allocated to the restore area')),
                ('used_bytes', sizefield.models.FileSizeField(default=0, help_text='Used value calculated by update method')),
            ],
        ),
        migrations.CreateModel(
            name='TapeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_path', models.CharField(db_index=True, help_text='logical path of archived files e.g. /badc/acsoe/file10.dat', max_length=2024)),
                ('size', sizefield.models.FileSizeField(help_text='size of file in bytes')),
                ('verified', models.DateTimeField(blank=True, help_text='Checked tape copy is same as disk copy', null=True)),
                ('stage', models.IntegerField(choices=[(1, 'On tape'), (2, 'Restoring'), (3, 'On Disk'), (0, 'Unverified'), (5, 'Restored')], db_index=True)),
                ('restore_disk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nla_control.RestoreDisk')),
            ],
        ),
        migrations.CreateModel(
            name='TapeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Human readable label for request', max_length=2024, null=True)),
                ('retention', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('active_request', models.BooleanField(default=False)),
                ('storaged_request_start', models.DateTimeField(blank=True, null=True)),
                ('storaged_request_end', models.DateTimeField(blank=True, null=True)),
                ('first_files_on_disk', models.DateTimeField(blank=True, null=True)),
                ('last_files_on_disk', models.DateTimeField(blank=True, null=True)),
                ('request_files', models.TextField(blank=True, help_text='Files selected for this request')),
                ('request_patterns', models.CharField(blank=True, default='', help_text='Original request patterns (first 2k)', max_length=2024, null=True)),
                ('notify_on_first_file', models.CharField(blank=True, help_text='email to notify on first files', max_length=2024, null=True)),
                ('notify_on_last_file', models.CharField(blank=True, help_text='email to notify on last files', max_length=2024, null=True)),
                ('files', models.ManyToManyField(help_text='The subset of files in the request that currently exist in the NLA system', to='nla_control.TapeFile')),
                ('quota', models.ForeignKey(help_text='User Quota for request', on_delete=django.db.models.deletion.CASCADE, to='nla_control.Quota')),
            ],
        ),
        migrations.CreateModel(
            name='StorageDSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, help_text='Process id for queue request', null=True)),
                ('host_ip', models.CharField(blank=True, help_text='ip address for the process', max_length=50, null=True)),
                ('request_dir', models.CharField(blank=True, help_text='temporary directory for retrive', max_length=500, null=True)),
                ('tape_request', models.ForeignKey(blank=True, help_text='Request being dealt with by storageD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nla_control.TapeRequest')),
            ],
        ),
    ]
