# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-21 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=2024)),
                ('size', models.BigIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageDSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, help_text=b'Process id for queue request', null=True)),
                ('host_ip', models.CharField(blank=True, help_text=b'ip address for the process', max_length=50, null=True)),
                ('request_dir', models.CharField(blank=True, help_text=b'temporary directory for retrive', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TapeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_path', models.CharField(help_text=b'logical path of archived files e.g. /badc/acsoe/file10.dat', max_length=2024)),
                ('size', models.BigIntegerField(help_text=b'size of file in bytes')),
                ('verified', models.DateTimeField(blank=True, help_text=b'Checked tape copy is same as disk copy', null=True)),
                ('stage', models.IntegerField(choices=[(1, b'On tape'), (2, b'Restoring'), (3, b'On Disk'), (0, b'Unverified'), (4, b'Deleted'), (5, b'Retored')])),
            ],
        ),
        migrations.CreateModel(
            name='TapeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text=b'Human readable label for request', max_length=2024, null=True)),
                ('retention', models.DateTimeField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('storaged_request_start', models.DateTimeField(blank=True, null=True)),
                ('storaged_request_end', models.DateTimeField(blank=True, null=True)),
                ('first_files_on_disk', models.DateTimeField(blank=True, null=True)),
                ('last_files_on_disk', models.DateTimeField(blank=True, null=True)),
                ('request_patterns', models.CharField(blank=True, default=b'', help_text=b'Original request patterns (fisrt 2k)', max_length=2024, null=True)),
                ('notify_on_first_file', models.CharField(blank=True, help_text=b'email to notify on first files', max_length=2024, null=True)),
                ('notify_on_last_file', models.CharField(blank=True, help_text=b'email to notify on last files', max_length=2024, null=True)),
                ('files', models.ManyToManyField(help_text=b'Files selected for this request', to='nla_control.TapeFile')),
                ('quota', models.ForeignKey(help_text=b'User Quota for request', on_delete=django.db.models.deletion.CASCADE, to='nla_control.Quota')),
            ],
        ),
        migrations.CreateModel(
            name='VerifyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_path', models.CharField(help_text=b'logical path of archived files e.g. /badc/acsoe/file10.dat', max_length=2024)),
                ('verified', models.DateTimeField(blank=True, help_text=b'Checked tape copy is same as disk copy', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='storagedslot',
            name='tape_request',
            field=models.ForeignKey(blank=True, help_text=b'Request being dealt with by storageD', null=True, on_delete=django.db.models.deletion.SET_NULL, to='nla_control.TapeRequest'),
        ),
    ]
