# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import sizefield.models


class Migration(migrations.Migration):

    dependencies = [
        ('nla_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountpoint', models.CharField(blank=True, help_text=b'E.g. /badc/restore_1', max_length=1024, unique=True)),
                ('allocated_bytes', sizefield.models.FileSizeField(default=0, help_text=b'Maximum size on the disk that can be allocated to the restore area')),
                ('used_bytes', sizefield.models.FileSizeField(default=0, help_text=b'Used value calculated by update method')),
            ],
        ),
        migrations.DeleteModel(
            name='VerifyLog',
        ),
        migrations.AddField(
            model_name='quota',
            name='email_address',
            field=models.CharField(blank=True, help_text=b'email address of user for notifications', max_length=2024, null=True),
        ),
        migrations.AddField(
            model_name='taperequest',
            name='active_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taperequest',
            name='request_files',
            field=models.TextField(blank=True, help_text=b'Files selected for this request'),
        ),
        migrations.AlterField(
            model_name='quota',
            name='size',
            field=sizefield.models.FileSizeField(help_text=b'size of file in bytes'),
        ),
        migrations.AlterField(
            model_name='tapefile',
            name='size',
            field=sizefield.models.FileSizeField(help_text=b'size of file in bytes'),
        ),
        migrations.AlterField(
            model_name='tapefile',
            name='stage',
            field=models.IntegerField(choices=[(1, b'On tape'), (2, b'Restoring'), (3, b'On Disk'), (0, b'Unverified'), (5, b'Restored')]),
        ),
        migrations.AlterField(
            model_name='taperequest',
            name='files',
            field=models.ManyToManyField(help_text=b'The subset of files in the request that currently exist in the NLA system', to='nla_control.TapeFile'),
        ),
        migrations.AlterField(
            model_name='taperequest',
            name='request_patterns',
            field=models.CharField(blank=True, default=b'', help_text=b'Original request patterns (first 2k)', max_length=2024, null=True),
        ),
        migrations.AddField(
            model_name='tapefile',
            name='restore_disk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nla_control.RestoreDisk'),
        ),
    ]
